### ISSUE TITLE
Takes to long until the camera is ready to capture

### ISSUE THREAD

**Issue by confile** [omergul123/LLSimpleCamera#33]
It takes very long until the camera is ready to capture. Compared with apps like Intagram. Is there a way to fix this?

**Comment by cameronehrlich** [comment]
I haven't used this library yet, although I am planning to.  The way i've solved this problem in the past is the begin initializing the capture session as soon a possible, before the user is even intending to enter "capture mode" yet.

**Comment by confile** [comment]
@cameronehrlich Could you post some code examples please?

**Comment by cameronehrlich** [comment]
Here is the code I used in one of [my apps](http://www.thememojiapp.com) in order to get the AVCaptureSession ready ASAP.  Basically, I kick of the session initialization when my model object is instantiated...which is pretty much immediately upon launch. 

https://gist.github.com/cameronehrlich/986c96fe35cc7f70aac2

I had to gut the rest of my model's code because it's a private repo, but I believe this will provide you with enough to get the "gist" of it. ;)  Let me know if anything is unclear.

**Comment by confile** [comment]
@cameronehrlich The ``my apps `` link is broken.

**Comment by cameronehrlich** [comment]
Thanks! Fixed it.

**Comment by confile** [comment]
Thank you very much

**Comment by cameronehrlich** [comment]
:+1:
